### PR TITLE
Fix invalid setting section IDs

### LINKED ISSUE #2854: App settings id contains translated strings
And therefor e.g. german Umlauts which is illegal.

### PR DESCRIPTION
**Pull request by nickvergessen**
Section titles were used before, but those are translated and can therefor
contain non-asci characters which are not allowed in HTML IDs.
Stripping them out is not possible as the remaining string might not be unique
anymore or even empty in case of languages with other charactersets like japanese

---

* This is a "save to backport" solution.
* For 5.4 or 6 we should consider making the ID non-optional to enforce good handling
* Sample PR for an app https://github.com/nextcloud/spreed/pull/7615

Fix  #2854

### CODE REVIEW

File: src/components/AppSettingsDialog/AppSettingsDialog.vue [hunk 1]
```diff
@@ -151,7 +151,9 @@ export default {
 
 	mounted() {
 		// Select first settings section
-		this.selectedSection = this.$slots.default[0].componentOptions.propsData.title
+		this.selectedSection = this.$slots.default[0].componentOptions.propsData.id ?
+			this.$slots.default[0].componentOptions.propsData.id :
+			this.$slots.default[0].componentOptions.propsData.title
```
Comment (Pytal) [inline src/components/AppSettingsDialog/AppSettingsDialog.vue:156]:
```suggestion
		this.selectedSection = this.$slots.default[0].componentOptions.propsData.id || this.$slots.default[0].componentOptions.propsData.title
```
**suggestion (non-blocking)**

File: src/components/AppSettingsDialog/AppSettingsDialog.vue [hunk 2]
```diff
@@ -178,26 +180,40 @@ export default {
 		 */
 		getSettingsNavigation(slots) {
 			// Array of navigationitems strings
-			const navigationItems = slots.filter(vNode => vNode.componentOptions).map(vNode => vNode.componentOptions.propsData?.title)
+			const navigationItems = slots.filter(vNode => vNode.componentOptions).map(vNode => {
+				return {
+					id: vNode.componentOptions.propsData?.id ? vNode.componentOptions.propsData?.id : vNode.componentOptions.propsData?.title,
```
Comment (Pytal) [inline src/components/AppSettingsDialog/AppSettingsDialog.vue:185]:
```suggestion
					id: vNode.componentOptions.propsData?.id || vNode.componentOptions.propsData?.title,
```
**suggestion (non-blocking)**

File: src/components/AppSettingsDialog/AppSettingsDialog.vue [hunk 3]
```diff
@@ -178,26 +180,40 @@ export default {
...
 			// Check for the uniqueness of section titles
 			navigationItems.forEach((element, index) => {
-				const newArray = [...navigationItems]
-				newArray.splice(index, 1)
-				if (newArray.indexOf(element) !== -1) {
+				const newTitlesArray = [...navigationTitles]
+				const newIdArray = [...navigationIds]
+				newTitlesArray.splice(index, 1)
+				newIdArray.splice(index, 1)
+				if (newTitlesArray.indexOf(element.title) !== -1) {
```
Comment (Pytal) [inline src/components/AppSettingsDialog/AppSettingsDialog.vue:198]:
```suggestion
				if (newTitlesArray.includes(element.title)) {
```
**suggestion (non-blocking)**

File: src/components/AppSettingsDialog/AppSettingsDialog.vue [hunk 4]
```diff
@@ -178,26 +180,40 @@ export default {
...
 					throw new Error(`Duplicate section title found: ${element}. Settings navigation sections must have unique section titles.`)
 				}
+				if (newIdArray.indexOf(element.id) !== -1) {
```
Comment (Pytal) [inline src/components/AppSettingsDialog/AppSettingsDialog.vue:201]:
```suggestion
				if (newIdArray.includes(element.id)) {
```
**suggestion (non-blocking)**

**Review by Pytal — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]
