### PR TITLE
Fix: Leftovers of `name` prop migration + fix `@` in user ids (richEditor)

### LINKED ISSUE #1825: User mention in comment field does not work for users with @ in name
First I thougt its solved with NC21. Selction works but we have users with special chars as "@" in their usernames. When I select one of those users the "@" inside the username is removed and so the user mention does not work

_Originally posted by @roadrunnerjb in https://github.com/nextcloud/server/issues/19523#issuecomment-810150432_

### PR DESCRIPTION
**Pull request by susnux**
### ☑️ Resolves

* Resolves #1825
* First commit is a follow up on #4106 

The first commit solves some issues / leftovers where the property was renamed but the example code was not changed.
The second commit solves an issues were mentioning users with `@` in there userid was not possible (`@` was removed).
Also added a note about the property renaming on the changelog previously only `name` -> `title` was mentioned and not `label` -> `title`.

New tests included.

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

File: src/components/NcRichContenteditable/NcAutoCompleteResult.vue [hunk 1]
```diff
@@ -51,7 +51,7 @@ export default {
 	name: 'NcAutoCompleteResult',
 
 	props: {
-		label: {
+		title: {
```
Comment (raimund-schluessler) [inline src/components/NcRichContenteditable/NcAutoCompleteResult.vue:54]: This change was intentional, because we agreed to use the term `title` only if if relates to the HTML attribute `title`, which it does not here.
Is there a deeper problem with renaming the prop here?

**Review by marcoambrosini — APPROVED** [review]

File: src/components/NcRichContenteditable/NcAutoCompleteResult.vue [hunk 2]
```diff
@@ -32,10 +32,10 @@
 			</div>
 		</div>
 
-		<!-- Label and subline -->
+		<!-- Title and subline -->
 		<span class="autocomplete-result__content">
-			<span class="autocomplete-result__label">
-				{{ label }}
+			<span class="autocomplete-result__title">
```
Comment (Antreesy) [inline src/components/NcRichContenteditable/NcAutoCompleteResult.vue:37]:
```suggestion
			<span class="autocomplete-result__title" :title="title">
```
The only thing I could suggest to justify this change, and to provide ability to see long names fully:
image

**Comment by susnux** [comment]
@Antreesy nice! Add the title prop :)

**Review by Antreesy — APPROVED** [review]
:seal:
