### PR TITLE
Use `NcActions` component for `NcAvatar`

### LINKED ISSUE #1683: Avatar popover glitch when opened the first time
### Steps

1. Open Nextcloud Talk
2. Create a conversation with a few participants
3. Open the conversation
4. Open the participants list
5. Click on the three dots on the avatars
6. Then do so again a few times

### Expected result
Popover always properly positioned.

### Actual result
Popover glitches from another position the first time it's rendered.
Then it moves to the correct position.
Subsequent clicks keeps it in the right position.

https://user-images.githubusercontent.com/277525/105861602-2fe08d80-5fef-11eb-9e6a-dec104f88f73.mp4

### Version
Talk master 525071cbe8581ca728233768b5f242c2835d69f9
Nextcloud-vue 3.5.2

This issue was already known and I had a workaround in https://github.com/nextcloud/nextcloud-vue/pull/831 but sadly wasn't accurate enough. Due to regressions I reverted the workaround as it wasn't useful enough in https://github.com/nextcloud/nextcloud-vue/issues/1681.

So this ticket here is to do further attempts at fixing this.
Might require digging deeper into v-tooltip->popper.js to find out why the position is initially incorrect.

### LINKED ISSUE #1762: Avatar menu alignment and sizing troubles
### Server side

On the server side in the sharing panel, there's a regression when upgrading from 3.2.0 to 3.7.2.

#### Before
image

#### After
image

### Talk app

In the Talk app the icon completely disappeared. This is because "Content.vue" from nextcloud-vue is applying `box-sizing: border-box` globally with v-deep! We better use explicit styling / overrides for this one in the avatar menu to make sure it can work everywhere.

image

When setting `box-sizing: content-box` the screenshot looks the same as on the server.

### Todos:

- [ ] add explicit `box-sizing: content-box` in the avatar menu item
- [ ] sort out alignment between icon and text

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This PR migrates the `NcAvatar` component from using the deprecated `NcPopoverMenu` to `NcActions`.

| Before | After |
|-|-|
| Screenshot 2023-04-29 at 13-06-41 Tasks - Nextcloud | Screenshot 2023-04-29 at 13-09-07 Tasks - Nextcloud |

Closes #1683, closes #1762

### CODE REVIEW

**Review by ShGKme — CHANGES_REQUESTED** [review]
The loading indicator is visible only on hover

NcAvatar

**Comment by raimund-schluessler** [comment]
> The loading indicator is visible only on hover
> 
> NcAvatar [ NcAvatar ](https://user-images.githubusercontent.com/25978914/235452981-83008cbf-f1f0-4782-8bd3-2ae1d837d992.gif) [ ](https://user-images.githubusercontent.com/25978914/235452981-83008cbf-f1f0-4782-8bd3-2ae1d837d992.gif)

Fixed.

File: src/components/NcAvatar/NcAvatar.vue [hunk 1]
```diff
@@ -710,28 +707,38 @@ export default {
...
-		.icon-more {
+		:deep(.action-item__menutoggle) {
 			cursor: pointer;
 			opacity: 0;
 		}
 		&:focus,
-		&:hover {
-			.icon-more {
+		&:hover,
+		&#{&}-loading {
```
Comment (nickvergessen) [inline src/components/NcAvatar/NcAvatar.vue:721]: What's that magic woodoo selector doing? 🪄

**Comment by skjnldsv** [comment]
> NcAvatar

I see something odd on the gif too.
On hover, the three dot should probably not be seen over the avatar, no?
The contrast is quite problematic. It should be full background colour with the three dot svg on top of it?

**Comment by raimund-schluessler** [comment]
> > NcAvatar
> I see something odd on the gif too. On hover, the three dot should probably not be seen over the avatar, no?

I think I don't really understand. When the menu is closed, and one hovers the avatar, the three dots icon shows up. This is how it is now already 🤔 

> The contrast is quite problematic. It should be full background colour with the three dot svg on top of it?

I don't know where this gif comes from, but I think there is something off with it. For me, the three dots have far more contrast, in an app and in the docs:

Screenshot 2023-05-09 at 09-32-43 Nextcloud Vue Style Guide

**Review by marcoambrosini — APPROVED** [review]

File: src/components/NcAvatar/NcAvatar.vue (hunk 1 above)
Comment (ShGKme) [inline src/components/NcAvatar/NcAvatar.vue:721]: Do we really need `.avatardiv--with-menu.avatardiv--with-menu-loading` here?

File: src/components/NcAvatar/NcAvatar.vue [hunk 2]
```diff
@@ -710,28 +707,38 @@ export default {
...
 		}
+		:deep() {
+			.button-vue,
+			.button-vue__icon {
+				height: var(--size);
+				min-height: var(--size);
+				width: var(--size) !important;
+				min-width: var(--size);
+			}
+		}
```
Comment (ShGKme) [inline src/components/NcAvatar/NcAvatar.vue:741]: Can we add a size/small prop to `NcButton`instead of deep internal classes overrides?

**Review by ShGKme — APPROVED** [review]
Works fine now

File: src/components/NcAvatar/NcAvatar.vue (hunk 1 above)
Comment (ShGKme) [reply src/components/NcAvatar/NcAvatar.vue:721]: `&` - parent selector, equals to `.avatardiv--with-menu`
`#{expression}` - interpolation, `#{$}` equals to value of `&`

So
```scss
.avatardiv {
    &--with-menu {
        &#{&}-loading {
            /* ... */
        }
    }
}
```

compiles to

```scss
.avatardiv--with-menu.avatardiv--with-menu-loading {
  /* ... */
}
```
