### PR TITLE
fix(NcModal): fix focus-trap fallback

### LINKED ISSUE #4265: Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
```js
Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at updateTabbableNodes (focus-trap.esm.js:328:1)
    at Object.activate (focus-trap.esm.js:590:1)
    at NcModal.js:2:1
    at u (NcModal.js:2:1)
    at Generator.<anonymous> (NcModal.js:2:1)
    at Generator.next (NcModal.js:2:1)
    at j (NcModal.js:2:1)
    at r (NcModal.js:2:1)
```

https://github.com/focus-trap/focus-trap/blob/a4b3948c7fce410841dc247227cbaa1292d2efcb/index.js#L286-L355

cc @susnux as you worked on this area before?

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #4265 

Sometimes the content is empty or not ready yet.

> `fallbackFocus` {HTMLElement | SVGElement | string | () => HTMLElement | SVGElement | string}: By default, an error will be thrown if the focus trap contains no elements in its tab order. With this option you can specify a fallback element to programmatically receive focus if no other tabbable elements are found. For example, you may want a popover's <div> to receive focus if the popover's content includes no tabbable elements. Make sure the fallback element has a negative tabindex so it can be programmatically focused. The option value can be a DOM node, a selector string (which will be passed to document.querySelector() to find the DOM node), or a function that returns any of these.

### CODE REVIEW

**Comment by susnux** [comment]
@skjnldsv something is wrong with the package lock: *20,786 additions, 2 deletions*
Are you using the correct node version?

File: src/components/NcModal/NcModal.vue [hunk 1]
```diff
@@ -707,11 +707,14 @@ export default {
 			// wait until all children are mounted and available in the DOM before focusTrap can be added
 			await this.$nextTick()
 
-			// Init focus trap
-			this.focusTrap = createFocusTrap(contentContainer, {
+			const options = {
 				allowOutsideClick: true,
+				fallbackFocus: contentContainer,
```
Comment (susnux) [inline src/components/NcModal/NcModal.vue:712]: > Make sure the fallback element has a negative tabindex so it can be programmatically focused.

The mask (== content container) does not have a negative tab index.

Comment (skjnldsv) [reply src/components/NcModal/NcModal.vue:712]: What if there is some focusable elements?
Will it still focus the first element or the mask then?

Comment (skjnldsv) [reply src/components/NcModal/NcModal.vue:713]: Pushed

**Comment by skjnldsv** [comment]
> @skjnldsv something is wrong with the package lock: _20,786 additions, 2 deletions_ Are you using the correct node version? As the lockfile version is also downgraded from 3 to 2 with this update.

Nice catch, haven't updated node on this terminal since the LTS merge

**Comment by skjnldsv** [comment]
Preview looks good, and content still focusable :+1:

**Review by susnux — APPROVED** [review]

**Review by szaimen — APPROVED** [review]

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/4270
