### PR TITLE
fix performance issue in isMobile

### LINKED ISSUE #577: Performance issues in App-Navigation
With #486, there was introduced a huge performance impact. I did some tests with [this App.vue](https://gist.github.com/korelstar/8d6fc42b8d69c2c84a70be298f39b451) (please use it within `vueexample` app). That app creates 200 `AppNavigationItem`s, each with three `ActionButton`s. It provides debug logs in the JavaScript console (please activate timestamps in your browser). After loading the app in your Nextcloud, please click the button "Toggle navigation" in order to show the 200 items and have a look at the console with debug logs.

Test environment:
- Firefox ESR 60.8 (Debian)
- Intel N3160 processor
Result: ~5-6 seconds

@skjnldsv wrote something about performance audits in browser tools. Here is what Firefox gave me:

<details>
<summary>Click to show screenshots</summary>

Screenshot

Screenshot
</details>

It looks like `isMobile` is the origin of the problem. After removing all `isMobile` stuff from `AppNavigationItem`, Firefox show me this:

<details>
<summary>Click to show screenshots</summary>

Screenshot

Screenshot
</details>

This looks much better!

2 seconds are still much, but this is far way better than 6 seconds.

What we have to do:
- [ ] replace `isMobile`by another solution. Maybe this could be realized in this case with CSS only?
- [ ] find more bottlenecks and eliminate them

### PR DESCRIPTION
**Pull request by korelstar**
fixes #577
uses the idea of @paulschwoerer (https://github.com/nextcloud/nextcloud-vue/issues/577#issuecomment-559399080) Thanks!!! :heart:

### CODE REVIEW

File: src/mixins/isMobile/index.js [hunk 1]
```diff
@@ -20,26 +20,24 @@
...
 		return {
-			isMobile: this._isMobile()
+			isMobile: false
 		}
 	},
-	beforeMount() {
-		window.addEventListener('resize', this._onResize)
+	mounted() {
+		IsMobileState.$on('changed', this.onIsMobileChanged)
+		this.isMobile = IsMobileState.isMobile
```
Comment (paulschwoerer) [inline src/mixins/isMobile/index.js]: This line should not be needed, as the initial state is `false` for both the mixin and the resize listener and the 'changed' event will fire if the state is changed to `true`. Also this depends on the internal structure of the `IsMobileState` component, which should be avoided.

Comment (korelstar) [reply src/mixins/isMobile/index.js]: This is needed if a component using this mixing is created after another component already used the mixin. In that case, `IsMobileState.isMobile` could be already set to `true` and no further event is fired. So we definitely need this!

Comment (paulschwoerer) [reply src/mixins/isMobile/index.js]: True! Did not think of that. Do you think it would make sense to watch changes to the [$listeners](https://vuejs.org/v2/api/#vm-listeners).changed property, so we can fire the 'changed' event every time a new listener joins? This would remove the coupling between the mixin and the component. Don't know if that's overkill though or would even introduce other side effects.

File: src/utils/IsMobileState.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
+/**
+ * @copyright Copyright (c) 2019 Nextcloud community
```
Comment (skjnldsv) [inline src/utils/IsMobileState.js]: please use the original creator of the file :)

File: src/utils/IsMobileState.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+ *
+ * @author Kristof Hamann
+ * @author Paul Schwörer
```
Comment (skjnldsv) [inline src/utils/IsMobileState.js]: feel free to enter your mail as well in copyrights :)

File: src/mixins/isMobile/index.js (hunk 1 above)
Comment (korelstar) [reply src/mixins/isMobile/index.js]: I'm not sure, I think it's fine as it is. What do you think, @skjnldsv ?

File: src/utils/IsMobileState.js (hunk 2 above)
Comment (korelstar) [reply src/utils/IsMobileState.js]: done :-)

File: src/mixins/isMobile/index.js (hunk 1 above)
Comment (skjnldsv) [reply src/mixins/isMobile/index.js]: I think we should try as much as possible to mimic the current behaviour which works very well (despite the performance issue) :)

Comment (korelstar) [reply src/mixins/isMobile/index.js]: Ok, this means LGTM?

Comment (skjnldsv) [reply src/mixins/isMobile/index.js]: If it works, yes? :p
