### PR TITLE
fix(NcRichContenteditable): Fix tribute emoji complete interfering unexpectedly aka. 🇨🇨 

### LINKED ISSUE #3825: Emoji picker suggestions are unexpected when using ":)" and ":D"
When typing `:)` and `:D`, two very common text emojis, the suggestions by the emoji picker are very off. And when you just press "enter", you get very misleading emojis as a result:

:) | :D 
-|-
image|image

Expected suggestions:
- :) = :slightly_smiling_face: `:slightly_smiling_face:`
- :D = :smile: `:smile:`

### PR DESCRIPTION
**Pull request by nickvergessen**
* Fix #3825 

## 🪦 Cocos-Island Meme

Bildschirmaufzeichnung vom 2023-03-24, 07-16-01

Opposed to #3923 I fixed it in `NcRichContenteditable` so that other components like the emoji picker itself are not interfered and still operate normally.

### CODE REVIEW

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 1]
```diff
@@ -273,16 +274,32 @@ export default {
 				// Where to inject the menu popup
 				menuContainer: this.menuContainer,
 				// Popup mention autocompletion templates
-				menuItemTemplate: item => `<span class="tribute-container-emoji__item__emoji">${item.original.native}</span> :${item.original.short_name}`,
+				menuItemTemplate: item => {
+					if (this.textEmojis.includes(item.original)) {
+						return item.original
+					}
```
Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:280]:
```suggestion
					// Return the raw string if there is no match
					if (this.textEmojis.includes(item.original)) {
						return item.original
					}
```

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 2]
```diff
@@ -388,6 +405,13 @@ export default {
 	},
 
 	mounted() {
+		const emojiCharacters = ['D', 'P', 'S', 'X', ')', '(', '/']
+		this.textEmojis = []
+		emojiCharacters.forEach((char) => {
+			this.textEmojis.push(':' + char)
+			this.textEmojis.push(':-' + char)
+		})
```
Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:413]: Please add comments about what's going on here

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 3]
```diff
@@ -273,16 +274,32 @@ export default {
...
 					emojiAddRecent(item.original)
 					return item.original.native
 				},
 				// Pass the search results as values
-				values: (text, cb) => cb(emojiSearch(text)),
+				values: (text, cb) => {
+					const emojiResults = emojiSearch(text)
+					if (this.textEmojis.includes(':' + text)) {
+						emojiResults.unshift(':' + text)
+					}
```
Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:300]: Please add comments about what's going on here

Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:300]: Please add comments about what's going on here

File: src/components/NcRichContenteditable/NcRichContenteditable.vue (hunk 2 above)
Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:413]: Please add comments about what's going on here

File: src/components/NcRichContenteditable/NcRichContenteditable.vue (hunk 1 above)
Comment (skjnldsv) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:280]:
```suggestion
					// Return the raw string if there is no match
					if (this.textEmojis.includes(item.original)) {
						return item.original
					}
```

**Review by skjnldsv — COMMENTED** [review]
See comments

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 4]
```diff
@@ -388,6 +414,17 @@ export default {
 	},
 
 	mounted() {
+		/**
+		 * Populate the list of text smiles we want to offer via Tribute.
+		 * We add the colon `:)` and colon-dash `:-)` version for each of them.
+		 */
+		const smilesCharacters = ['D', 'P', 'S', 'X', ')', '(', '/']
```
Comment (ChristophWurst) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:421]: what about lowercase p and s? :p

Comment (nickvergessen) [reply src/components/NcRichContenteditable/NcRichContenteditable.vue]: done

**Review by skjnldsv — APPROVED** [review]
Sure!

**Review by ChristophWurst — APPROVED** [review]
Looks good

**Review by mejo- — CHANGES_REQUESTED** [review]
To be honest, I think that #3923 is the cleaner approach. It doesn't affect the `EmojiPicker` component either, the search function is only used by emoji autocompletion implementions in `NcRichContenteditable` and Text/Collectives. That's also why I think that it's the proper place to fix this.

**Review by mejo- — APPROVED** [review]
Let's get this in nevertheless.
